### ISSUE TITLE
targetDB update KeyError

### ISSUE THREAD

**Issue by psterk** [sdecesco/targetDB#5]
I have updated my targetDB installations on macOS Catalina and Ubuntu 18.04 and was able to run it in single mode, but when I run it in list mode, I get the following errors and it then hangs until I exit with ctrl-C. Any clues what might be wrong?

`[NAME CONVERSION]: Converting gene names into IDs (Uniprot,Ensembl,HGNC)
[NAME CONVERSION]: Conversion Done
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/sterk/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/targetDB/utils/targetDB_gui.py", line 396, in launch
    dr.get_list_excel(self.gene_df)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/targetDB/druggability_report.py", line 911, in get_list_excel
    data = data[col_order]
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['Male tissues', 'Muscle tissues', 'Female tissues', 'Bone marrow & lymphoid tissues', 'Endocrine tissues', 'Adipose & soft tissue', 'Liver & gallbladder', 'Gastrointestinal tract', 'Kidney & urinary bladder', 'Proximal digestive tract'] not in index"
`

**Comment by sdecesco** [comment]
Could you provide info on the database file that you use ? it needs to be the latest version of it otherwise it will raise this error.

**Comment by psterk** [comment]
TargetDB_20_12_19.db 
MD5 (TargetDB_20_12_19.db) = 75c06373fad62a6db585cb8206f3d30c

**Comment by sdecesco** [comment]
This is the right one. Is it a clean install ? Have you just updated the database path in the config before running ? If this is the case you need to close and restart targetDB for the path change to take effect (I will flag it as a bug and correct it in future update)

**Comment by psterk** [comment]
This is a clean install, if I try install again, it looks like everything is ok (anaconda python 3.7):

$ pip3 install targetDB                                         
Requirement already satisfied: targetDB in /Users/sterk/anaconda3/lib/python3.7/site-packages (1.3.0)
Requirement already satisfied: intermine in /Users/sterk/anaconda3/lib/python3.7/site-packages (from targetDB) (1.11.0)
Requirement already satisfied: pandas>=0.21.0 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from targetDB) (0.24.2)
Requirement already satisfied: scipy in /Users/sterk/anaconda3/lib/python3.7/site-packages (from targetDB) (1.3.0)
Requirement already satisfied: opentargets in /Users/sterk/anaconda3/lib/python3.7/site-packages (from targetDB) (3.1.16)
Requirement already satisfied: xmltodict in /Users/sterk/anaconda3/lib/python3.7/site-packages (from targetDB) (0.12.0)
Requirement already satisfied: matplotlib in /Users/sterk/anaconda3/lib/python3.7/site-packages (from targetDB) (3.1.0)
Requirement already satisfied: biopython in /Users/sterk/anaconda3/lib/python3.7/site-packages (from targetDB) (1.76)
Requirement already satisfied: pytz>=2011k in /Users/sterk/anaconda3/lib/python3.7/site-packages (from pandas>=0.21.0->targetDB) (2019.1)
Requirement already satisfied: numpy>=1.12.0 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from pandas>=0.21.0->targetDB) (1.16.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from pandas>=0.21.0->targetDB) (2.8.0)
Requirement already satisfied: cachecontrol==0.11.6 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from opentargets->targetDB) (0.11.6)
Requirement already satisfied: future==0.16.0 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from opentargets->targetDB) (0.16.0)
Requirement already satisfied: PyYAML in /Users/sterk/anaconda3/lib/python3.7/site-packages (from opentargets->targetDB) (5.1.1)
Requirement already satisfied: addict in /Users/sterk/anaconda3/lib/python3.7/site-packages (from opentargets->targetDB) (2.2.1)
Requirement already satisfied: requests<3.0 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from opentargets->targetDB) (2.22.0)
Requirement already satisfied: cycler>=0.10 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from matplotlib->targetDB) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from matplotlib->targetDB) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from matplotlib->targetDB) (2.4.0)
Requirement already satisfied: six>=1.5 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas>=0.21.0->targetDB) (1.12.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from requests<3.0->opentargets->targetDB) (2019.6.16)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from requests<3.0->opentargets->targetDB) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from requests<3.0->opentargets->targetDB) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/sterk/anaconda3/lib/python3.7/site-packages (from requests<3.0->opentargets->targetDB) (3.0.4)
Requirement already satisfied: setuptools in /Users/sterk/anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->targetDB) (41.0.1)


After restarting targetDB, I now get the following errors:

[NAME CONVERSION]: Converting gene names into IDs (Uniprot,Ensembl,HGNC)
[NAME CONVERSION]: Conversion Done
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/sterk/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/targetDB/utils/targetDB_gui.py", line 396, in launch
    dr.get_list_excel(self.gene_df)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/targetDB/druggability_report.py", line 835, in get_list_excel
    data = td.get_descriptors_list(gene_ids, targetdb=targetDB)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/targetDB/target_descriptors.py", line 813, in get_descriptors_list
    if cell_values.loc[(tid, 'Kidney', 'kidney')].value > avg_exp_1stddev or cell_values.loc[
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 873, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/Users/sterk/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 221, in _has_valid_tuple
    raise IndexingError('Too many indexers')
pandas.core.indexing.IndexingError: Too many indexers

**Comment by sdecesco** [comment]
if sensitive could you privately send me the target you're trying so I can try to reproduce it locally

**Comment by psterk** [comment]
It happens with the two example targets DYRK1A, CYP3D6 (and other targets I have tried. Same happens on an older installation that I have just updated.

**Comment by sdecesco** [comment]
I can't reproduce the issue. from what I see in the above message it seems to be a problem with the pandas package. Can you update pandas ? as I'm using pandas 0.25.3 and you are using 0.24.2

If this is the case I will specify a version higher in the dependencies. 

Let me know.

**Comment by psterk** [comment]
I've upgraded to the latest version from the anaconda channel:
pandas             pkgs/main::pandas-0.24.2-py37h0a44026~ --> anaconda::pandas-1.0.3-py37h6c726b0_0

This appears to solve the problem: [NAME CONVERSION]: Converting gene names into IDs (Uniprot,Ensembl,HGNC)
[NAME CONVERSION]: Conversion Done
[EXPORT]: Excel file:  [Export_2_entries_22Apr2020_142047.xlsx]  successfully generated

**Comment by sdecesco** [comment]
Great I'll update the dependencies then to capture that. 

Thanks for your patience to figure that one out ;-)
