### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by Acribbs** [sdecesco/targetDB#7]
Hi Stephane,

I found this tool through Benedikt Kessler and it looks cool. I was hoping to try and run it on one of our projects. 

Despite not installing it yet (I will get around to that soon), I was wondering if it would be possible to update the running instructions so they are a little more detailed? 

Also, do you intend on releasing this as a Conda package? Im happy to help if needed.

Adam

**Comment by Acribbs** [comment]
Sorry I should have been a little more specific, I'm referring to documentation about the two different entry points into your script. 

`target_DB` and `targetDB` what is the difference in the functionality of these two entry points?

**Comment by sdecesco** [comment]
Hi Adam, 

Thanks for the interest. I shipped targetDB as a Pypi package at the moment but not Conda. If you have any good tip for that I'm willing to give it a go. 

For the documentation, you're right and it's probably long overdue a good update of the readme file.

To answer quickly your questions though, here are the two handles features: 

targetDB : Simply starts the GUI nothing else

target_DB: Is a pure command line entry point used when I generate the TargetDB databases, it is not necessarily maintained with the ambition to be always working as sometime it will break if one of the data source I use are changing their outputs, so I end up updating this part of the code everytime I generate an update to the library. But for full transparence here are the option for this entry point: 

![image](https://user-images.githubusercontent.com/36763600/80088242-243dd300-8554-11ea-913e-736ef33d0ac0.png)


PS: I will also very shortly upload a full tutorial presentation

**Comment by Acribbs** [comment]
I can look into creating a Conda package, shouldn't be too difficult, the only thing I think that may need some thought is that your package requires the ChEMBL v24 database as an external dependancy. Don't think there is a way to ship this in Conda. However, it shouldn't prevent a Conda package creation.

**Comment by Acribbs** [comment]
Just looking over the requirements of your package so a Conda release can be attempted, are there any dependancies outside of the standard library that I'm missing (I was sure Tkinter is not part of the Std lib but it is)?
```
 - python
 - biopython
 - intermine
 - matplotlib
 - mysqlclient
 - numpy
 - opentargets
 - pandas
 - pkg_resources
 - requests
 - scikit-learn
 - scipy
 - seaborn
 - xmltodict
 - blast
 - Fpocket
```

**Comment by sdecesco** [comment]
Thanks for looking into that, 

there is also:
- xlsxwriter 
and pandas should be this version or above:
- pandas >=0.25.3

I saw you listed blast and fpocket there. Is it fine if these are not python packages ? never used condas packaging so I don't know limitations etc...

**Comment by Acribbs** [comment]
Ok great, no the great thing is that Conda is cross platform, it originally started as a python package manager but because it relies on installing the binaries it can literally package anything. 

Ok, I can make a start on the Conda package and see how far I get. Will likely add this to Bioconda and tag you into the commit

**Comment by Acribbs** [comment]
Ah this is going to be a little bit more of a pain than I thought, I will probably have to build the opentargets Conda package too. I have started on the targetsdb here: https://github.com/bioconda/bioconda-recipes/pull/21780. Its currently failing because its missing the opentargets dependancy. In the meantime would you be able to look over the meta.yml and see if I have included all the dependancies?

**Comment by sdecesco** [comment]
It looks fine to me

**Comment by Acribbs** [comment]
The code package was merged and I am happy for you to close the issue whenever you are happy. Thanks

**Comment by sdecesco** [comment]
Great ! Thanks again for your help
