### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Acribbs** [sdecesco/targetDB#8]
While testing the Conda package (Im hopefully nearly there). I found syntax errors, it seems you are returning a print statement. While it won't affect the Conda package it may be be best to fix and make a new pypi release so the Conda package is up to date.

Affected lines are here:

https://github.com/sdecesco/targetDB/blob/db51481d5aa491f3e14379ede3dfb64e4a6c7645/targetDB/druggability_report.py#L804

https://github.com/sdecesco/targetDB/blob/9863eaf20159d8bc77f0ae246cfebb77b463603b/targetDB/druggability_report.py#L814

**Comment by sdecesco** [comment]
Thanks Adam, It's fixed in my local version. I have a few other tweaks to do before committing and pushing it to here but will do shortly.

**Comment by Acribbs** [comment]
Ok great, I will close this issue. Thanks and looking forward to giving it a go.
